name: travenor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8

  equatable: ^2.0.7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.10
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  flutter_svg: ^2.2.0
  firebase_remote_config: ^5.4.7
  readmore: ^3.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  scrollable_positioned_list: ^0.3.8
  grpc: ^4.1.0
  protobuf: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: 'sf'
      fonts:
        - asset: assets/font/sf-ui-display-black.otf
        - asset: assets/font/sf-ui-display-bold.otf
        - asset: assets/font/sf-ui-display-heavy.otf
        - asset: assets/font/sf-ui-display-light.otf
        - asset: assets/font/sf-ui-display-medium.otf
        - asset: assets/font/sf-ui-display-semibold.otf
        - asset: assets/font/sf-ui-display-thin.otf
        - asset: assets/font/sf-ui-display-ultralight.otf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
  icon_background_color: "#24BAEC"

flutter_native_splash:
  color: "#24BAEC"
  image: assets/appicon.png


  android_12:
    color: "#24BAEC"
    image: assets/appicon.png