name: travenor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8

  equatable: ^2.0.7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

fonts:
  - family: sf
    fonts:
      - assets: assets/font/sf-ui-display-black.otf
      - assets: assets/font/sf-ui-display-bold.otf
      - assets: assets/font/sf-ui-display-heavy.otf
      - assets: assets/font/sf-ui-display-light.otf
      - assets: assets/font/sf-ui-display-medium.otf
      - assets: assets/font/sf-ui-display-semibold.otf
      - assets: assets/font/sf-ui-display-thin.otf
      - assets: assets/font/sf-ui-display-ultralight.otf
